[package]
name = "inference"
version = "0.1.0"
edition = "2023_10"

[dependencies]
node__operators_0_root_nodes = { path = "../initializers/node__operators_0_root_nodes"} 
node__operators_0_root_biases = { path = "../initializers/node__operators_0_root_biases"} 
node__operators_0_tree_indices = { path = "../initializers/node__operators_0_tree_indices"} 
node__operators_0_leaf_nodes = { path = "../initializers/node__operators_0_leaf_nodes"} 
node__operators_0_nodes_0 = { path = "../initializers/node__operators_0_nodes_0"} 
node__operators_0_nodes_1 = { path = "../initializers/node__operators_0_nodes_1"} 
node__operators_0_nodes_2 = { path = "../initializers/node__operators_0_nodes_2"} 
node__operators_0_biases_0 = { path = "../initializers/node__operators_0_biases_0"} 
node__operators_0_biases_1 = { path = "../initializers/node__operators_0_biases_1"} 
node__operators_0_biases_2 = { path = "../initializers/node__operators_0_biases_2"} 
_operators_0_constant_value = { path = "../attributes/_operators_0_constant_value"} 
_operators_0_constant_1_value = { path = "../attributes/_operators_0_constant_1_value"} 
_operators_0_constant_2_value = { path = "../attributes/_operators_0_constant_2_value"} 
_operators_0_constant_3_value = { path = "../attributes/_operators_0_constant_3_value"} 
_operators_0_constant_4_value = { path = "../attributes/_operators_0_constant_4_value"} 
_operators_0_constant_5_value = { path = "../attributes/_operators_0_constant_5_value"} 
_operators_0_constant_6_value = { path = "../attributes/_operators_0_constant_6_value"} 
_operators_0_constant_7_value = { path = "../attributes/_operators_0_constant_7_value"} 
_operators_0_constant_8_value = { path = "../attributes/_operators_0_constant_8_value"} 
_operators_0_constant_9_value = { path = "../attributes/_operators_0_constant_9_value"} 
_operators_0_constant_10_value = { path = "../attributes/_operators_0_constant_10_value"} 
constant_57_value = { path = "../attributes/constant_57_value"} 
orion = { git = "https://github.com/gizatechxyz/orion.git", rev = "57871a4" } 
